---
title: "espn crawling/scraping"
author: "Nick"
date: "1/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
library(rvest)
library(janitor)
```

```{r read base url}
base.url = read_html("https://www.espn.com/nfl/teams")
```

```{r}
#grab team names from base url
teams <- base.url %>% 
  html_nodes(".h5") %>% 
  html_text()
teams = teams[1:32]
```

```{r }
#grab urls to each team schedule
url <- base.url %>% 
  html_nodes(".nowrap:nth-child(2) .AnchorLink") %>% 
  html_attr("href") %>% 
  paste("https://www.espn.com", ., sep = "") 
url = url[1:32]

#bind teams and url
team.links = tibble(teams, url)
```

```{r scrape schedules}
#get game IDs
results_list <- tibble(
  html_results = map(team.links$url[1:32],
    ~ {
      
      Sys.sleep(2)
      # DO THIS!  sleep 2 will pause 2 seconds between server requests to avoid being identified and potentially blocked / assume crawling bot is a DNS attack.
      .x %>%
        read_html()
    }),
  summary_url = team.links$url[1:32]
)
```

```{r get game IDs from schedules}
game.ids <- tibble(summary_url = results_list$summary_url, 
                          team = 
                            map(results_list$html_results,
                                ~ .x %>%
                                  html_nodes("#fittPageContainer .db") %>%
                                  html_text()
                                ),
                          game =
                            map(results_list$html_results,
                                ~ .x %>%
                                  html_nodes(".ml4 .AnchorLink") %>%
                                  html_attr("href")
                                )
)
```

```{r disaggregate results}
#create df of game links 
game.links <- game.ids %>% 
  select(team, game) %>% 
  pivot_wider(., names_from = team, values_from = game) %>% 
  drop_na() %>% 
  clean_names() %>% 
  pivot_longer(cols = c("c_buffalo_bills":"c_seattle_seahawks")) %>% 
  unnest(cols = everything())
game.links$name <- sub("c_*", "", game.links$name)

#single out ids + build new links to game data table, unique removes duplicates that were scraped twice due to away + home teams
game.links$id = substr(game.links$value,40,49) #40 through 49 are characters to extract for game id
game.links <- game.links %>% 
  transmute(url = glue::glue("https://www.espn.com/nfl/matchup?gameId={id}")) %>% unique()

```

```{r scrape game data}
#get game stats
games_list <- tibble(
  html_results = map(game.links$url[1:2],
    ~ {
      Sys.sleep(2)
      .x %>%
        read_html()
    }),
  summary_url = game.links$url[1:2]
)
```

```{r df for data}
#create dataframe of game data
game.data <- tibble(summary_url = games_list$summary_url, 
            
                   home = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".home .short-name") %>%
                                  html_text()
                                ),
                   away = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".away .short-name") %>%
                                  html_text()
                                ),
                   line = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".odds-lines-plus-logo li:nth-child(1)") %>%
                                  html_text()
                                ),
                   over = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes("#gamepackage-game-information li+ li") %>%
                                  html_text()
                                ),
                   home_score =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes("#gamepackage-matchup-wrap .icon-font-before") %>%
                                  html_text()
                                ),
                   away_score = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes("#gamepackage-matchup-wrap .icon-font-after") %>%
                                  html_text()
                                ),
                   home_first_d =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes("#teamstats-wrap .highlight:nth-child(1) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_first_d = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes("#teamstats-wrap .highlight:nth-child(1) td:nth-child(2)") %>%
                                  html_text()
                                ),
                   home_plays =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(7) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_plays = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(7) td:nth-child(2)") %>%
                                  html_text()
                                ),
                   home_yards =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(8) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_yards = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(8) td:nth-child(2)") %>%
                                  html_text()
                                ),
                   home_drives =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(9) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_drives = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(9) td:nth-child(2)") %>%
                                  html_text()
                                ),
                   home_yds_play =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(10) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_yds_play = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(10) td:nth-child(2)") %>%
                                  html_text()
                                ),
                   home_pass_yds =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(11) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_pass_yds = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(11) td:nth-child(2)") %>%
                                  html_text()
                                ),
                   home_pass_att =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".indent:nth-child(12) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_pass_att = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".indent:nth-child(12) td:nth-child(2)") %>%
                                  html_text()
                                ),
                   home_int =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".indent:nth-child(14) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_int = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".indent:nth-child(14) td:nth-child(2)") %>%
                                  html_text()
                                ),
                   home_sack =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".indent:nth-child(15) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_sack = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".indent:nth-child(15) td:nth-child(2)") %>%
                                  html_text()
                                ),
                   home_rush_yds =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(16) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_rush_yds = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(16) td:nth-child(2)") %>%
                                  html_text()
                                ),
                   home_red_zone =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(19) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_red_zone = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(19) td:nth-child(2)") %>%
                                  html_text()
                                ),
                   home_pen =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(20) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_pen = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(20) td:nth-child(2)") %>%
                                  html_text()
                                ), 
                   home_fumble =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".indent:nth-child(22) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_fumble = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".indent:nth-child(22) td:nth-child(2)") %>%
                                  html_text()
                                ), 
                   home_def_td =  map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(24) td~ td+ td") %>%
                                  html_text()
                                ),
                   away_def_td = map(games_list$html_results,
                                ~ .x %>%
                                  html_nodes(".highlight:nth-child(24) td:nth-child(2)") %>%
                                  html_text()
                                ) 
)
```
